# Generated by Django 4.2.16 on 2024-10-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottiimage',
            name='hash',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
