# Generated by Django 4.2.16 on 2024-10-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_lottiimage_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottiimage',
            name='hash',
            field=models.CharField(blank=True, default='', max_length=64, unique=True),
        ),
    ]
