# Generated by Django 4.2.16 on 2024-10-11 05:52

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_lottiimage_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottiimage',
            name='image',
            field=models.ImageField(upload_to=images.models.LottiImage.upload_to),
        ),
    ]
